package storage

import (
	"bytes"
	"context"
	"encoding/base64"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"

	"english-learning-mcp/internal/domain"
)

// Python consumes these exact Go-generated bytes, rather than hashing fixtures
// produced by a second copy of its own serialization algorithm.
func TestExportVocabularyGolden(t *testing.T) {
	ctx := context.Background()
	store, err := Open(ctx, ":memory:")
	if err != nil {
		t.Fatal(err)
	}
	defer store.Close()
	owner := "owner:日本語"
	compare := func(name string) {
		t.Helper()
		snapshot, err := store.ExportVocabulary(ctx, owner, "english-mcp")
		if err != nil {
			t.Fatal(err)
		}
		actual, err := json.MarshalIndent(snapshot, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		actual = append(actual, '\n')
		path := filepath.Join("testdata", "export-"+name+".json")
		if os.Getenv("UPDATE_EXPORT_GOLDEN") == "1" {
			if err := os.WriteFile(path, actual, 0o644); err != nil {
				t.Fatal(err)
			}
		}
		want, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(actual, want) {
			t.Fatalf("%s drifted; inspect the contract change, then regenerate with UPDATE_EXPORT_GOLDEN=1 and run the Python contract tests", path)
		}
	}
	compare("empty")
	now := time.Date(2026, 9, 1, 12, 0, 0, 123456789, time.UTC)
	png, _ := base64.StdEncoding.DecodeString("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=")
	image, err := store.StoreMedia(ctx, MediaInsert{ContentType: "image/png", Data: png, SourceURL: "https://dictionary.example/image.png", Now: now})
	if err != nil {
		t.Fatal(err)
	}
	audio, err := store.StoreMedia(ctx, MediaInsert{ContentType: "audio/mpeg", Data: []byte("ID3\x04\x00\x00\x00\x00\x00\x00"), SourceURL: "https://dictionary.example/audio.mp3", Now: now})
	if err != nil {
		t.Fatal(err)
	}
	definition := domain.DictionaryDefinition{
		Definition: "A river bank <land> & café\u2028line\u2029paragraph 🦆", // exercises Go's HTML-safe and Unicode escaping
		Images:     []domain.DictionaryImage{{ImageURL: image.SourceURL, MediaID: image.ID, ThumbnailURL: image.SourceURL, ThumbnailMediaID: image.ID}},
		// Nil examples/phrases/labels intentionally cover nested null lists.
	}
	lookup := domain.DictionarySnapshotData{
		Status: 200, SourceURL: "https://dictionary.example/bank?x=1&y=2",
		Entries: []domain.DictionaryEntry{{Headword: "bank", PartOfSpeech: "noun",
			Pronunciations: domain.DictionaryPronunciations{UK: "bæŋk"},
			Audio:          &domain.DictionaryAudioRegions{UK: &domain.DictionaryAudio{AudioURL: audio.SourceURL, ContentType: audio.ContentType, MediaID: audio.ID}},
			Definitions:    []domain.DictionaryDefinition{definition},
		}},
	}
	encoded, err := json.Marshal(lookup)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := store.sql.Exec(`INSERT INTO dictionary_snapshots
		(id, provider, normalized_term, status, source_url, parser_version, dataset_version, data_json, fetched_at, expires_at, active)
		VALUES ('lookup-golden', 'cambridge', 'bank', 200, ?, 14, '', ?, ?, ?, 1)`, lookup.SourceURL, string(encoded), TimeString(now), TimeString(now)); err != nil {
		t.Fatal(err)
	}
	selected, err := json.Marshal(definition)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := store.sql.Exec(`INSERT INTO vocabulary_items
		(id, owner_key, term, normalized_term, learning_status, usefulness, personal_interest, lookup_id,
		context, sense_key, selected_entry_index, selected_definition_index, selected_definition_json,
		custom_description, description_source_json, notes_json, examples_json, tags_json, created_at, updated_at)
		VALUES ('item-rich', ?, 'bank', 'bank', 'learned', 'high', 'low', 'lookup-golden',
		'café beside water', 'dictionary-golden', 0, 0, ?, ?, ?, ?, ?, ?, ?, ?)`,
		owner, string(selected), "Saved <meaning> & café\u2028line\u2029paragraph 🦆",
		`{"title":"Page <one> & café","url":"https://example.test/café?a=1&b=2"}`, `["Use the river sense.","日本語"]`, `["A duck sat on the bank."]`, `["nature","tag & <quoted>"]`, TimeString(now), TimeString(now)); err != nil {
		t.Fatal(err)
	}
	if _, err := store.sql.Exec(`INSERT INTO vocabulary_images (id, owner_key, vocabulary_item_id, media_id, original_filename, example, created_at)
		VALUES ('attachment-golden', ?, 'item-rich', ?, 'café.png', 'A duck & a river', ?)`, owner, image.ID, TimeString(now)); err != nil {
		t.Fatal(err)
	}
	if _, err := store.sql.Exec(`INSERT INTO vocabulary_items
		(id, owner_key, term, normalized_term, learning_status, context, sense_key, created_at, updated_at)
		VALUES ('item-minimal', ?, 'quiet', 'quiet', 'archived', 'context-only meaning', 'context:golden', ?, ?)`, owner, TimeString(now), TimeString(now)); err != nil {
		t.Fatal(err)
	}
	compare("full")
}
